Added comment on FFmpeg audio stream copy regression
error: 'codec frame size is not set'
seen with lavc versions 54.x.x using the "new" audio enc/dec API
only way past this I'm aware of is to force audio re-encoding